language: java
jdk: openjdk8

script:
  - ./mvnw clean install -B

before_install:
  - export TZ=GMT

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/gcloud-service-key.json.enc
    - PROJECT_NAME_PRD=apactestdeploy
    - CLUSTER_NAME_PRD=apac-demo
    - CLOUDSDK_COMPUTE_ZONE=us-central1-b
    - DOCKER_IMAGE_NAME=apac-demo
    - KUBE_DEPLOYMENT_NAME=apac-demo
    - KUBE_DEPLOYMENT_CONTAINER_NAME=apac-demo
    - NODES_NUM=3
    - GCLOUD_MACHINE_TYPE=n1-standard-1

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: chmod +x deploy-production.sh && ./deploy-production.sh
    skip_cleanup: true
    on:
      branch: master
