apiVersion: v1
kind: Service
metadata:
  name: spring-boot-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: apac-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080