kind: Service
apiVersion: v1
metadata:
  name: spring-boot-node-service
  labels:
    app: apac-demo
spec:
  type: NodePort
  selector:
    app: apac-demo
  ports:
    - port: 80
      targetPort: 8080